export type Locale = "zh" | "en";

export const company = {
  stockCode: "01520",
  phone: "(852) 3159 6960",
  email: "info@vmh.com.hk",
  website: "vmh.com.hk",
  addressZh: "香港中環德輔道中19號環球大廈17樓1702室",
  addressEn: "Room 1702, 17/F, World-Wide House, 19 Des Voeux Road Central, Hong Kong",
};

export const siteCopy = {
  zh: {
    name: "天機控股有限公司",
    shortName: "天機控股",
    legalName: "天機控股有限公司",
    tagline: "VMH — Building the Next Generation IP Economy",
    taglineSecondary: "構建下一代 IP 經濟生態",
    description: "以 IP 為核心，連接人工智能、機器人與算力基礎設施，推動文化、旅遊、體育等產業的數字化與全球商業化。",
    nav: [
      ["主頁", "/"],
      ["關於我們", "/#about"],
      ["業務範疇", "/#services"],
      ["企業新聞", "/news"],
      ["投資者關係", "/investors"],
      ["聯繫我們", "/#contact"],
    ] as const,
    language: "EN",
    languageHref: "/en",
    investorAction: "查看投資者資料",
    investorHref: "/investors",
    latestFiling: "最新公告",
    download: "下載 PDF",
    aboutTitle: "连接产业、科技与数字未来",
    aboutLead: "以产业投资为基础，以科技创新为驱动，持续布局具备长期价值与增长潜力的多元业务。",
    aboutParagraphs: [
      "天机控股有限公司为香港主板上市公司，业务围绕多元产业投资、科技创新及数字经济展开，持续发掘具备长期发展潜力的优质项目与产业机会。",
      "集团重点关注 IP产业、人工智能、文化旅游及娱乐事业、数字资产技术与创新应用等领域，通过资本、产业资源、技术能力及全球合作网络，推动传统产业与新经济深度融合。",
      "在IP及文化产业领域，我们关注优质内容、文化资产与品牌IP的长期价值，并探索其在文旅、娱乐、消费及数字化场景中的多元发展。",
      "在人工智能及数字科技领域，我们积极布局AI应用、数字平台及相关技术服务，为不同产业提供创新解决方案，并持续探索数字资产技术在实体经济中的应用价值。",
      "天机控股致力于连接资本、科技、文化与产业，为合作伙伴创造可持续的商业价值，并把握新一轮全球数字经济的发展机遇。",
    ],
    servicesTitle: "業務範疇",
    servicesLead: "連接人工智能、機器人、體育文化與數字基礎設施的重點項目。",
    services: [
      {
        slug: "mokenlogic-harness",
        title: "MokenLogic Harness",
        text: "面向持續學習的 macOS 智能體環境，連接長期專案狀態、應用程式、瀏覽器工作階段、檔案與工具。",
      },
      {
        slug: "greater-bay-area-hunan-football-team",
        title: "大灣區湖南人足球隊",
        text: "天機控股支持的體育 IP 項目，以足球連接大灣區湘籍社群、湖南文化與城市交流。",
      },
      {
        slug: "dolphinode",
        title: "Dolphinode",
        text: "由天機控股孵化，將數字技術、數字資產服務、市場增長與長期營運納入同一服務體系。",
      },
    ],
    viewCase: "查看項目",
    newsTitle: "企業新聞",
    newsLead: "了解公司的最新合作、產品與發展。",
    allNews: "查看全部新聞",
    investorsTitle: "投資者關係",
    investorsLead: "公告、通函、財務報告與企業管治資料集中查閱。",
    allFilings: "查看全部公告",
    contactTitle: "商務合作",
    contactLead: "如需企業、品牌或投資者相關資訊，請與我們聯繫。",
    footerIncorporation: "於開曼群島註冊成立的有限公司",
    terms: "使用條款",
    privacy: "私隱政策",
    rights: "版權所有",
  },
  en: {
    name: "VM Holding Company Limited",
    shortName: "VM Holding",
    legalName: "VM Holding Company Limited",
    tagline: "VMH — Building the Next Generation IP Economy",
    taglineSecondary: "",
    description: "With IP at its core, VMH connects artificial intelligence, robotics and computing infrastructure to advance the digital transformation and global commercialisation of culture, tourism, sports and related industries.",
    nav: [
      ["Home", "/en"],
      ["About", "/en#about"],
      ["Business", "/en#services"],
      ["News", "/en/news"],
      ["Investors", "/en/investors"],
      ["Contact", "/en#contact"],
    ] as const,
    language: "繁中",
    languageHref: "/",
    investorAction: "Investor information",
    investorHref: "/en/investors",
    latestFiling: "Latest filing",
    download: "Download PDF",
    aboutTitle: "Connecting IP with the digital economy",
    aboutLead: "Trusted technology and long-term operations help established IP build sustainable digital value.",
    aboutParagraphs: [
      "VM Holding Company Limited is an innovative company focused on the IP digital economy, providing full-cycle ecosystem development and operations for IP holders and brands.",
      "In a user-centric digital economy, we bring together digital technologies, identity verification systems, industry specialists and enterprises to connect physical and digital experiences.",
      "We aim to become a global digital value hub for IP, helping enterprises transform IP products and enable information, capital and technology to flow more effectively.",
    ],
    servicesTitle: "Business scope",
    servicesLead: "Priority initiatives connecting artificial intelligence, robotics, sports culture and digital infrastructure.",
    services: [
      {
        slug: "mokenlogic-harness",
        title: "MokenLogic Harness",
        text: "A macOS agent environment for continual learning, connecting long-lived project state with applications, browser sessions, files and tools.",
      },
      {
        slug: "greater-bay-area-hunan-football-team",
        title: "Greater Bay Area Hunan Football Team",
        text: "A VMH-supported sports IP initiative connecting Hunan communities, culture and regional exchange through football.",
      },
      {
        slug: "dolphinode",
        title: "Dolphinode",
        text: "Incubated by VMH, bringing together digital technology, digital-asset services, market growth and long-term operations in one service system.",
      },
    ],
    viewCase: "View project",
    newsTitle: "Corporate news",
    newsLead: "Company partnerships, product updates and developments.",
    allNews: "View all news",
    investorsTitle: "Investor relations",
    investorsLead: "Announcements, circulars, financial reports and governance information in one place.",
    allFilings: "View all filings",
    contactTitle: "Business enquiries",
    contactLead: "Contact us for corporate, partnership or investor-related information.",
    footerIncorporation: "Incorporated in the Cayman Islands with limited liability",
    terms: "Terms of use",
    privacy: "Privacy policy",
    rights: "All rights reserved",
  },
} as const;
