export type Locale = "zh" | "en";

export const company = {
  stockCode: "01520",
  phone: "(852) 3159 6960",
  email: "info@vmh.com.hk",
  website: "vmh.com.hk",
  addressZh: "香港中環德輔道中19號環球大廈17樓1702室",
  addressEn: "Room 1702, 17/F, World-Wide House, 19 Des Voeux Road Central, Hong Kong",
};

export const siteCopy = {
  zh: {
    name: "天機控股有限公司",
    shortName: "天機控股",
    legalName: "天機控股有限公司",
    tagline: "VMH — Building the Next Generation IP Economy",
    taglineSecondary: "構建下一代 IP 經濟生態",
    description: "以 IP 為核心，連接人工智能、機器人與算力基礎設施，推動文化、旅遊、體育等產業的數字化與全球商業化。",
    nav: [
      ["主頁", "/"],
      ["關於我們", "/#about"],
      ["業務範疇", "/#services"],
      ["企業新聞", "/news"],
      ["投資者關係", "/investors"],
      ["聯繫我們", "/#contact"],
    ] as const,
    language: "EN",
    languageHref: "/en",
    investorAction: "查看投資者資料",
    investorHref: "/investors",
    latestFiling: "最新公告",
    download: "下載 PDF",
    aboutTitle: "連接IP與數字經濟",
    aboutLead: "以可信技術與長期運營，協助優秀IP建立可持續的數字價值。",
    aboutParagraphs: [
      "天機控股有限公司是一家專注於IP數字經濟領域的創新企業，致力於通過前沿技術為IP持有方和品牌方提供全周期的IP生態構建與運營服務。",
      "在以用戶為中心的數字經濟時代，我們以數字技術與實名認證體系為支撐，聚合各行業的專家與企業，共建連接實體與數字世界的智能生態系統。",
      "我們希望成為全球IP的數字化價值樞紐，協助企業完成IP產品數字化轉型，讓信息、資本與技術更有效地流轉。",
    ],
    servicesTitle: "業務範疇",
    servicesLead: "連接人工智能、機器人、體育文化與數字基礎設施的重點項目。",
    services: [
      {
        slug: "mokenlogic-harness",
        title: "MokenLogic Harness",
        text: "面向持續學習的 macOS 智能體環境，連接長期專案狀態、應用程式、瀏覽器工作階段、檔案與工具。",
      },
      {
        slug: "greater-bay-area-hunan-football-team",
        title: "大灣區湖南人足球隊",
        text: "天機控股支持的體育 IP 項目，以足球連接大灣區湘籍社群、湖南文化與城市交流。",
      },
      {
        slug: "dolphinode",
        title: "Dolphinode",
        text: "由天機控股孵化，將數字技術、數字資產服務、市場增長與長期營運納入同一服務體系。",
      },
    ],
    viewCase: "查看項目",
    newsTitle: "企業新聞",
    newsLead: "了解公司的最新合作、產品與發展。",
    allNews: "查看全部新聞",
    investorsTitle: "投資者關係",
    investorsLead: "公告、通函、財務報告與企業管治資料集中查閱。",
    allFilings: "查看全部公告",
    contactTitle: "商務合作",
    contactLead: "如需企業、品牌或投資者相關資訊，請與我們聯繫。",
    footerIncorporation: "於開曼群島註冊成立的有限公司",
    terms: "使用條款",
    privacy: "私隱政策",
    rights: "版權所有",
  },
  en: {
    name: "VM Holding Company Limited",
    shortName: "VM Holding",
    legalName: "VM Holding Company Limited",
    tagline: "VMH — Building the Next Generation IP Economy",
    taglineSecondary: "",
    description: "With IP at its core, VMH connects artificial intelligence, robotics and computing infrastructure to advance the digital transformation and global commercialisation of culture, tourism, sports and related industries.",
    nav: [
      ["Home", "/en"],
      ["About", "/en#about"],
      ["Business", "/en#services"],
      ["News", "/en/news"],
      ["Investors", "/en/investors"],
      ["Contact", "/en#contact"],
    ] as const,
    language: "繁中",
    languageHref: "/",
    investorAction: "Investor information",
    investorHref: "/en/investors",
    latestFiling: "Latest filing",
    download: "Download PDF",
    aboutTitle: "Connecting IP with the digital economy",
    aboutLead: "Trusted technology and long-term operations help established IP build sustainable digital value.",
    aboutParagraphs: [
      "VM Holding Company Limited is an innovative company focused on the IP digital economy, providing full-cycle ecosystem development and operations for IP holders and brands.",
      "In a user-centric digital economy, we bring together digital technologies, identity verification systems, industry specialists and enterprises to connect physical and digital experiences.",
      "We aim to become a global digital value hub for IP, helping enterprises transform IP products and enable information, capital and technology to flow more effectively.",
    ],
    servicesTitle: "Business scope",
    servicesLead: "Priority initiatives connecting artificial intelligence, robotics, sports culture and digital infrastructure.",
    services: [
      {
        slug: "mokenlogic-harness",
        title: "MokenLogic Harness",
        text: "A macOS agent environment for continual learning, connecting long-lived project state with applications, browser sessions, files and tools.",
      },
      {
        slug: "greater-bay-area-hunan-football-team",
        title: "Greater Bay Area Hunan Football Team",
        text: "A VMH-supported sports IP initiative connecting Hunan communities, culture and regional exchange through football.",
      },
      {
        slug: "dolphinode",
        title: "Dolphinode",
        text: "Incubated by VMH, bringing together digital technology, digital-asset services, market growth and long-term operations in one service system.",
      },
    ],
    viewCase: "View project",
    newsTitle: "Corporate news",
    newsLead: "Company partnerships, product updates and developments.",
    allNews: "View all news",
    investorsTitle: "Investor relations",
    investorsLead: "Announcements, circulars, financial reports and governance information in one place.",
    allFilings: "View all filings",
    contactTitle: "Business enquiries",
    contactLead: "Contact us for corporate, partnership or investor-related information.",
    footerIncorporation: "Incorporated in the Cayman Islands with limited liability",
    terms: "Terms of use",
    privacy: "Privacy policy",
    rights: "All rights reserved",
  },
} as const;
